### ISSUE TITLE
ValueError at /admin/translation_manager/translationentry/make/ invalid literal for float(): 1.4.19

### ISSUE THREAD

**Issue by ruddy200** [COEXCZ/django-translation-manager#1]
Having version like 1.4.19 raises error due to version checking
in

_translation_manager/management/commands/makemessages.py in handle_noargs_

58:            if 1.7 > float(django.get_version()) >= 1.6:

**Comment by michalkaspar** [comment]
We don't have this on our roadmap. If you still want it, we will be grateful if you do pull request.
