### ISSUE TITLE
translation frontend form fields overlap with filter sidebar in new Django 1.9 admin

### ISSUE THREAD

**Issue by macolo** [COEXCZ/django-translation-manager#16]
![image](https://cloud.githubusercontent.com/assets/4056979/11901660/102840fc-a5ad-11e5-8cac-1daf04306e76.png)

Can somebody reproduce this?

**Comment by Visgean** [comment]
![screenshot from 2015-12-18 17-40-16](https://cloud.githubusercontent.com/assets/193832/11901915/7f78c480-a5ae-11e5-9584-7d42461be928.png)
Do you use any special skins / styles for admin?

**Comment by Visgean** [comment]
Oh never mind, I can reproduce it with different window size..

**Comment by Visgean** [comment]
This is more of Django admin bug, since we don't have any custom styles. You can solve this in two ways:
- use Django Suit 
- set custom css overflow-x for admin templates, but you will have to deal with the filters somehow...

**Comment by macolo** [comment]
Hey, thanks for your investigation. I went back to have a look at it and see now that the content is not cut off, in fact, there is a horizontal scroll bar at the bottom of the main content that let's users have access to the initially hidden part of the main content.

I agree that this is not a bug, it's bad UX from the Django admin side.

Many thanks for your time and all the best
