### ISSUE TITLE
[Errno 2] No such file or directory: 'locale/de/LC_MESSAGES/django.po'

### ISSUE THREAD

**Issue by macolo** [COEXCZ/django-translation-manager#18]
this happens, when translation strings are imported through the db but the locale directory structure is not there yet. Example: Import DB from a production system to a local system and then click on 'publish translations'.

I would expect this to work as it works when I create the /locale directory structure without the *.po files. In this case the *.po files are correctly written.

**Comment by michalkaspar** [comment]
Hi,
in which version this is happening?
