### ISSUE TITLE
ValueError at /backoffice/translation_manager/translationentry/ too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by ruddy200** [COEXCZ/django-translation-manager#2]
Following options from example raise error.

TRANSLATIONS_CUSTOM_FILTERS = [
    _('admin-translation_manager-filter-title'),
    [
         ('^admin-', 'admin-_'),
         ('^front-', 'front-_'),
         ('^email-', 'email-*'),
    ]
]

**Comment by michalkaspar** [comment]
Comment in defaults is imprecisely formulated.

It should by only one list with tuples containing regex and label, for example:

TRANSLATIONS_CUSTOM_FILTERS = [
    (r'^admin-', 'Admin fields'),
    (r'^test-', 'Test fields'),
]

I rephrased the comment above TRANSLATION_CUSTOM_FILTERS in defaults
