### ISSUE TITLE
hints could show comments for translators

### ISSUE THREAD

**Issue by rafael-h-ferreira** [COEXCZ/django-translation-manager#20]
Django makemessages command reads the comments made with the keyword "Translators": https://docs.djangoproject.com/en/1.10/topics/i18n/translation/#comments-for-translators

django-translation-manager could pick that up and show it in the translating table, on the admin.

**Comment by michalkaspar** [comment]
Hello,

thank you for a good idea, but we dont have this feature on our roadmap.

We reallly appreciate your help in the form of PR.

**Comment by cisarpavel** [comment]
Not in plan for now. Thanks for idea. All PRs are appreciated.
