### ISSUE TITLE
Broken migration

### ISSUE THREAD

**Issue by Krakenus** [COEXCZ/django-translation-manager#23]
Na branchi **feature/remote_sync** způsobuje migrace _0006_auto_20170915_1529_ error:
`TypeError: 'class Meta' got invalid attribute(s): indexes`

Pomohlo odstranění [řádku 22](https://github.com/COEXCZ/django-translation-manager/blob/aafc0dfa0d673a841215fd69e742a4ae7429a77e/translation_manager/migrations/0006_auto_20170915_1529.py#L22).

**Comment by cisarpavel** [comment]
Solved. Thanks for reporting.
