### ISSUE TITLE
No module named policy

### ISSUE THREAD

**Issue by fabiocaccamo** [COEXCZ/django-translation-manager#31]
I just installed this package on a project running on `python 2.7` and `django 1.11`, and I receive the following error:
```
File "/home/arexons/projects/arexons/arexons_dev/local/lib/python2.7/site-packages/translation_manager/admin.py", line 1, in <module>
    from email.policy import HTTP
ImportError: No module named policy
```

**Comment by fabiocaccamo** [comment]
I just installed `0.5.1` version and the `ImportError` is not raised.

**Comment by fabiocaccamo** [comment]
What is this?
https://github.com/COEXCZ/django-translation-manager/blob/923c9981341167faa63b732f14cc735cca31b673/translation_manager/admin.py#L1

It is not used, I removed it and everything works fine.

**Comment by Krakenus** [comment]
The import has been already removed so I'm closing the issue.
